### PR TITLE
Cope with missing images when adding background size

### LINKED ISSUE #12: Process fails when images are missing
When using the `detectImageSize` option, the whole process will stop if a source image doesn't exist.

Is this by design? CSS/browsers are tolerant of missing images, I feel postcss-at2x should follow that approach.

### PR DESCRIPTION
**Pull request by tdhooper**
Fixes #12

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ function getBackgroundImageSize(decl, existingBackgroundSize, detectImageSize, r
           prop: 'background-size',
           value: `${size.width}px ${size.height}px`,
         });
-      });
+      }).catch(() => {});
```
Comment (simonsmith) [inline lib/index.js]: Why is this needed?

Comment (tdhooper) [inline lib/index.js]: Stops it raising uncaught error in promise

Comment (simonsmith) [inline lib/index.js]: 👍 

Do we have any useful information in the `Error` that could perhaps be logged out to the console?

Comment (simonsmith) [inline lib/index.js]: With `result.warn` - https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#32-use-resultwarn-for-warnings

Comment (tdhooper) [inline lib/index.js]: Good idea!

File: lib/index.js [hunk 2]
```diff
@@ -116,6 +123,8 @@ function getBackgroundImageSize(decl, existingBackgroundSize, detectImageSize, r
           prop: 'background-size',
           value: `${size.width}px ${size.height}px`,
         });
+      }).catch((err) => {
+        warn(err);
```
Comment (simonsmith) [inline lib/index.js]: Could this be simplified to `.catch(warn)`?

Comment (tdhooper) [inline lib/index.js]: Unfortunately not, I think it might return another resolved promise that doesn't pass `existingBackgroundSize`, so we end up with:

     @media (min-device-pixel-ratio: 1.5), (min-resolution: 144dpi), (min-resolution: 1.5dppx) {
       .dog {
         background-image: url('./test/fixtures/images/dog@2x.jpg');
    +    undefined: undefined;
       }
     }

Comment (simonsmith) [inline lib/index.js]: Fair enough 👍

**Comment by simonsmith** [comment]
Another nice addition. Thanks

**Comment by simonsmith** [comment]
Published in `3.2.0`. Thanks @tdhooper
